
export const GET_ALL_ACTIVITES="GET_ALL_ACTIVITES";
export const GET_ACTIVITY_BY_ID="GET_ACTIVITY_BY_ID";
export const ADD_ACTIVITY="ADD_ACTIVITY";
export const DELETE_ACTIVITY="DELETE_ACTIVITY";
export const UPDATE_ACTIVITY="UPDATE_ACTIVITY";