
export const GET_ALL_ACTIVITES="GET_ALL_ACTIVITES";
export const MARK_ACTIVITY_EDITABLE="MARK_ACTIVITY_EDITABLE";
export const UNMARK_ACTIVITY_EDITABLE="UNMARK_ACTIVITY_EDITABLE";
export const ADD_ACTIVITY="ADD_ACTIVITY";
export const DELETE_ACTIVITY="DELETE_ACTIVITY";
export const UPDATE_ACTIVITY="UPDATE_ACTIVITY";