
export const GET_ALL_ACTIVITES="GET_ALL_ACTIVITES";
export const MARK_ACTIVITY_EDITABLE="MARK_ACTIVITY_EDITABLE";
export const UNMARK_ACTIVITY_EDITABLE="UNMARK_ACTIVITY_EDITABLE";
export const WAIT="WAIT";
export const ERROR="ERROR";